### ISSUE TITLE
Stuttering while building new cells

### ISSUE THREAD

**Issue by daniel-mf** [ASGAlex/flame_spatial_grid#2]
I created a simple setup with a moving player and I'm experiencing some stutter.
The joystick is present in the example just to help seeing the stutter with debug set to off, but it still stutters if you remove it and move the player in some other way. Debug mode off makes the stutter a lot weaker, but still present.

Is this an expected behavior in the current state of the project?

https://github.com/ASGAlex/flame_spatial_grid/assets/4193707/81d2a830-feb0-45f8-aceb-574f5df2aa9a

```dart
import 'dart:async';

import 'package:flame/components.dart';
import 'package:flame/extensions.dart';
import 'package:flame/game.dart';
import 'package:flame/palette.dart';
import 'package:flame_spatial_grid/flame_spatial_grid.dart';

const _debugEnabled = true;

class MinimalGame extends FlameGame with HasSpatialGridFramework {
  MinimalGame();

  final world = MyWorld();
  late final CameraComponent cameraComponent;
  late final JoystickComponent joystick;

  @override
  FutureOr<void> onLoad() async {
    _createJoystick();

    final player = Player(position: Vector2.zero());

    cameraComponent = CameraComponent(
      world: world,
      hudComponents: [joystick, FpsTextComponent()],
    );
    cameraComponent.viewfinder.zoom = 1;
    cameraComponent.priority = 999;
    cameraComponent.follow(player, maxSpeed: 200, snap: true);

    await initializeSpatialGrid(
      cellSize: 50,
      rootComponent: world,
      trackedComponent: SpatialGridDebugCameraWrapper(cameraComponent),
      trackWindowSize: false,
      debug: _debugEnabled,
    );

    add(world);
    world.add(player);

    return super.onLoad();
  }

  void _createJoystick() {
    joystick = JoystickComponent(
      knob: CircleComponent(
        radius: 25,
        paint: BasicPalette.lightBlue.paint(),
      ),
      background: CircleComponent(
        radius: 100,
        paint: BasicPalette.blue.paint(),
      ),
      position: Vector2.all(100),
    );
  }
}

class SpatialGridDebugCameraWrapper extends SpatialGridCameraWrapper {
  SpatialGridDebugCameraWrapper(super.cameraComponent);

  @override
  void onAfterZoom() {
    try {
      if (!game.isSpatialGridDebugEnabled) {
        game.onAfterZoom();
      }
      // ignore: avoid_catches_without_on_clauses, empty_catches
    } catch (e) {}
  }
}

class Player extends PositionComponent
    with HasGridSupport, HasPaint, HasGameRef<MinimalGame> {
  Player({super.position})
      : super(
          size: Vector2(25, 25),
          anchor: Anchor.center,
        ) {
    paint.color = BasicPalette.yellow.color;
    debugMode = _debugEnabled;
  }

  late final _rect = Rect.fromLTWH(0, 0, size.x, size.y);

  @override
  void render(Canvas canvas) {
    canvas.drawRect(_rect, paint);
  }

  @override
  void update(double dt) {
    super.update(dt);
    if (!game.joystick.delta.isZero()) {
      position.add(
        game.joystick.relativeDelta * 100 * dt,
      );
    }
  }
}

class MyWorld extends World {}

```

**Comment by ASGAlex** [comment]
This is expected behavior because you player leaves preloaded game field and triggers creating new cells with (probably) new components inside. Than more components you will have inside than longer the game will freeze. 

I try eventually optimize the process but anyway it is blocking by-design, especially with single-threaded language like Dart =( 

To avoid stutter in your game you should play with grid parameters: 
 - cellSize: should not be too big but maybe it is better to make it 10 times bigger than your average component size;
 - activeRadius, unloadRadius, preloadRadius - to find balanced combination of active vs pre-build cells
 - processCellsLimitToPauseEngine - if you need sometimes to build very large field of cells
 - buildCellsPerUpdate / cleanupCellsPerUpdate

You can read details in `initializeSpatialGrid` dartdoc, and play with parameters to find which fits with your game conditions. 

Also, keep in mind that debug overlay is completelly unoptimized, so keeping it constantly enabled will cause a heavy FPS drop. But you can toggle it in runtime.

**Comment by ASGAlex** [comment]
@daniel-mf did you found a solution for your case? 
For your example it is only necessary to change `processCellsLimitToPauseEngine ` to larger value (default is 5) to prevent engine pausing while building new cells. But in games with complex logic it may become a reason of bugs. In this cause it become better to pause whole game during loading.

**Comment by daniel-mf** [comment]
Hey @ASGAlex, I ended up writting my own very basic spatial grid system (just grid mapping and some basic grid state management). But anyway, I'm just making some tests for a possible personal game code base.
I'll try to tweak those parameters as suggested as soon as I have an opportunity to do so.
Thanks for the tips!
